services:
  app:
    image: localhost/symfony-openapi-playground
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/var/www/app
    entrypoint: "./docker/php/entrypoint.sh"
    ports:
      - '8000:8000'
