services:
  app:
    image: localhost/symfony-openapi-playground
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/var/www/app
    entrypoint: "./docker/php/entrypoint.sh"
    ports:
      - "8000:8000"

  postgresql:
    image: docker.io/postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data:rw

  adminer:
    image: docker.io/adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: postgresql
