openapi: 3.0.0

info:
  title: Marx Attack API
  description: There is no description yet
  version: 0.0.1

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/events:
    post:
      operationId: createEvent
      summary: Creates an event and returns it
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewEvent"
      responses:
        "200":
          description: A JSON object containing the created event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListItem"
    get:
      operationId: listEvents
      summary: Returns a list of events.
      tags:
        - Events

      responses:
        "200":
          description: A JSON array of events
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListPagination"
              example:
                count: 2
                current: 1
                next: null
                previous: null
                items:
                  - id: 1
                    name: "My First Event"
                  - id: 2
                    name: "My Second Event"
components:
  schemas:
    Pagination:
      type: object
      properties:
        count:
          type: integer
          example: 2
        current:
          type: integer
          example: 2
        next:
          type: integer
          nullable: true
          example: 3
        previous:
          type: integer
          nullable: true
          example: 1
        items:
          type: array
          items:
            type: object

    NewEvent:
      type: object
      properties:
        name:
          type: string
          minLength: 5
          maxLength: 50
          example: "My super event"
      required:
        - name

    EventListItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "My super event"

    EventListPagination:
      allOf:
        - $ref: "#/components/schemas/Pagination"
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/EventListItem"
