openapi: 3.0.0

info:
  title: Marx Attack API
  description: There is no description yet
  version: 0.0.1

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/login:
    post:
      operationId: login
      summary: Logs the user in and returns the token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: A JSON object containing the created event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /api/events:
    post:
      operationId: createEvent
      summary: Creates an event and returns it
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewEvent"
      responses:
        "200":
          description: A JSON object containing the created event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListItem"
    get:
      operationId: listEvents
      summary: Returns a list of events.
      tags:
        - Events

      responses:
        "200":
          description: A JSON array of events
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListPagination"
              example:
                count: 2
                current: 1
                next: null
                previous: null
                items:
                  - id: 550e8400-e29b-41d4-a716-446655440000
                    name: "My First Event"
                  - id: 550e8400-e29b-41d4-a716-446655443333
                    name: "My Second Event"

  /api/events/{eventUuid}:
    get:
      operationId: getEvent
      summary: Returns am event's details
      tags:
        - Events
      parameters:
        - in: path
          name: eventUuid
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the event to get

      responses:
        "200":
          description: A JSON object of the event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventListItem"
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Login:
      type: object
      properties:
        username:
          type: string
          minLength: 5
          maxLength: 50
          example: "admin"
        password:
          type: string
          minLength: 5
          maxLength: 50
          example: "secret"
      required:
        - username
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          minLength: 5
          maxLength: 50
          example: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0MzQ3Mjc1MzYsInVzZXJuYW1lIjoia29ybGVvbiIsImlhdCI6IjE0MzQ2NDExMzYifQ.nh0L_wuJy6ZKIQWh6OrW5hdLkviTs1_bau2GqYdDCB0Yqy_RplkFghsuqMpsFls8zKEErdX5TYCOR7muX0aQvQxGQ4mpBkvMDhJ4-pE4ct2obeMTr_s4X8nC00rBYPofrOONUOR4utbzvbd4d2xT_tj4TdR_0tsr91Y7VskCRFnoXAnNT-qQb7ci7HIBTbutb9zVStOFejrb4aLbr7Fl4byeIEYgp2Gd7gY"

    Pagination:
      type: object
      properties:
        count:
          type: integer
          example: 2
        current:
          type: integer
          example: 2
        next:
          type: integer
          nullable: true
          example: 3
        previous:
          type: integer
          nullable: true
          example: 1
        items:
          type: array
          items:
            type: object

    NewEvent:
      type: object
      properties:
        name:
          type: string
          minLength: 5
          maxLength: 50
          example: "My super event"
      required:
        - name

    EventListItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        name:
          type: string
          example: "My super event"
        owner:
          type: string
          example: admin

    EventListPagination:
      allOf:
        - $ref: "#/components/schemas/Pagination"
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/EventListItem"
